ExternalMergeSort
FileManager* ExternalMergeSort::fileManager
Указатель на класс файл-менеджера.
Указатель на класс файл-менеджера, осуществляющий взаимодействие сортировки с файловой системой.
Referenced by setParams, externalSort, createRuns, ~ExternalMergeSort.
long long ExternalMergeSort::sizeOfSegments
Размер сегментов.
Размер сегментов, на которые изначально будет поделена последовательность.
Referenced by setParams, externalSort, createRuns.
bool ExternalMergeSort::ok
Флаг готовности сортировки.
Флаг установлен в true, если все параметры заданы корректно и false, если нет.
Referenced by ExternalMergeSort, setParams, createRuns.
LogType ExternalMergeSort::log
Тип логгирования.
Without - логгирование не ведется, File - логгирование ведется в файл, CLI - логгирование ведется в консоль.
Referenced by ExternalMergeSort, setLog, print.
Counter ExternalMergeSort::counter
Счетчик.
Счетчик сортировки, подсчитывает характеристики сортировки.
Referenced by BubbleExternalSort::sort, externalSort, createRuns, mergeSequencesNew, HeapExternalSort::siftDown, HeapExternalSort::sort, QuickExternalSort::qSortI.
Response ExternalMergeSort::createRuns(long long *size)
Чтение входной последовательности из файла.
size Размер входной последовательности. Код успеха или ошибки. Считывает последовательности длиной size, сортирует их методом перегруженным в производных классах и записывает в один из буферных файлов.
References ok, ParamsFail, WriteOnly, sizeOfSegments, MemoryError, FileManager::clearOutFile, Success, fileManager, FileManager::read, counter, Counter::incFileOp, print, sort, FileManager::write, FileManager::closeOFile, EndOfFile.
Referenced by externalSort.
Response ExternalMergeSort::mergeSequencesNew(FileManager *input1, FileManager *input2, FileManager *out, long long size)
Слияние последовательностей.
input1 Первый входной файл. input2 Второй входной файл. out Выходной файл. size Размер сегментов Код успеха или ошибки. Сливает последовательность длиной size из input1 с последовательностью длиной sizr из input2, результат записывает в out.
References FileManager::getEndOfFile, FileManager::read, counter, Counter::incComparsion, FileManager::write, FileManager::closeOFile, EndOfFile, Success.
Referenced by externalSort.
void ExternalMergeSort::print(const char *msg)
Логгирование.
msg Сообщение, которое необходимо записать в лог. Записывает msg в лог в зависимости от атрибута log.
References log, WithOut, CLI.
Referenced by externalSort, createRuns.
virtual void ExternalMergeSort::sort(long long *arr, long long size)=0
Сортирует последовательность длиной size одним из методов, перегруженных в производных классах.
arr Массив, который необходимо отсортировать. size Длина массива. Чисто виртуальный метод. Перегружен в производных классах. Сортирует последовательность длиной size одним из методов, перегруженных в производных классах.
Referenced by createRuns.
ExternalMergeSort::ExternalMergeSort()
Пустой конструктор класса.
Обнуляет атрибуты.
References ok, log, CLI.
ExternalMergeSort::ExternalMergeSort(FileManager *file, long long sizeOfSegments)
Конструктор класса.
file Файл-менеджер, отвечающий за взаимодействие сортировки с файловой системой. sizeOfSegments Размер сегментов. Вызывет setParams(...), если код возврата не Success, бросает исключение.
References setParams, Success, log, CLI.
Response ExternalMergeSort::setParams(FileManager *file, long long sizeOfSegments)
Определение параметров сортировки.
file Файл-менеджер, отвечающий за взаимодействие сортировки с файловой системой. sizeOfSegments Размер сегментов. Код успеха или ошибки. Задает параметры сортировки, если это возможно. Устанавливает ok в true или возвращает код ошибки. Возвращает код успеха или ошибки.
References FileManager::getState, ReadAndWrite, ok, FileManagerFail, SizeError, FileManager::checkForEquality, InputAndOutputIsEqual, sizeOfSegments, fileManager, Success.
Referenced by ExternalMergeSort, UserInterface::setParams.
Response ExternalMergeSort::externalSort()
Вызывает метод внешней многофазной сортировки.
Код успеха или ошибки. Осуществляет внешнюю многофазную сортировку слиянием. Вызывает createRuns(...), mergeSequncesNew(...).
References counter, Counter::clear, Counter::setBegTime, print, createRuns, FileManager::clearOutFile, sizeOfSegments, FileManager::setEndOfFile, FileManager::closeIFile, mergeSequencesNew, Counter::incFileOp, EndOfFile, fileManager, Counter::setEndTime, Success.
void ExternalMergeSort::setLog(LogType log)
Устанавливает тип логгирования.
log Тип логгирования. Задает тип логгирования: WithOut - без логгирования, File - логгирование в файл log.txt, CLI - логгирование в консоль.
References log.
ExternalMergeSort::~ExternalMergeSort()
Пустой виртуальный деструктор класса.
Освобождает выделенную память.
References fileManager.