Counter
long long Counter::begTime
Начальное время.
Число тактов программы на момент начала сортировки.
Referenced by setBegTime, getTimeInterval, clear.
long long Counter::endTime
Конечное время.
Число тактов программы на момент оконачания сортировки.
Referenced by setEndTime, getTimeInterval, clear.
long long Counter::comparsion
Число сравнений.
Referenced by incComparsion, getComparsion, clear.
long long Counter::fileOp
Число операций с файлами.
Число записей в файл и чтений из файла чисел.
Referenced by incFileOp, getFileOp, clear.
long long Counter::swaps
Число перестановок.
Подсчет производится только в методе внутренней сортировки, т.к. вне её не имеет смысла.
Referenced by incSwaps, getSwaps, clear.
Counter::Counter()
Пустой конструктор класса.
Обнуляет счетчие.
References clear.
void Counter::setBegTime()
Задание начальной точки отсчета.
Присваивает атрибуту begTime текущее число тактов работы программы.
References begTime.
Referenced by ExternalMergeSort::externalSort.
long long Counter::setEndTime()
Задание конечной точки отсчета. /return Возвращает число миллисекунд между моментами begTime и endTime.
Присваивает атрибуту endTime текущее число тактов работы программы.
References endTime, getTimeInterval.
Referenced by ExternalMergeSort::externalSort.
long long Counter::getTimeInterval()
Получение временного интервала. /return Возвращает число миллисекунд между моментами begTime и endTime.
Подсчитывает временной интервал в миллисекундах работы программы от момента begTime до момента endTime.
References endTime, begTime.
Referenced by setEndTime.
void Counter::incSwaps()
Увеличение счетчика перестановок.
Увеличивает на единицу счетчик перестановок, задаваемоый атрибутом swaps.
References swaps.
Referenced by BubbleExternalSort::sort, HeapExternalSort::siftDown, HeapExternalSort::sort, QuickExternalSort::qSortI.
long long Counter::getSwaps()
Получение счетчика перестановок. /return Число перестановок, задаваемое атрибутом swaps.
Получает число перестановок, задаваемое атрибутом swaps.
References swaps.
void Counter::incComparsion(long long n)
Увеличение счетчика сравнений.
n Число, на которое будет увеличиваться счетчик сравнений. Увеличивает счетчик перестановок, задаваемый атрибутом comparsion, на n.
References comparsion.
Referenced by BubbleExternalSort::sort, ExternalMergeSort::mergeSequencesNew, HeapExternalSort::siftDown, QuickExternalSort::qSortI.
long long Counter::getComparsion()
Получение счетчика сравнений. /return Число сравнений, задаваемое атрибутом comparsion.
Получает число сравнений, задаваемое атрибутом comparsion.
References comparsion.
void Counter::incFileOp(long long n)
Увеличение счетчика числа операций с файлами.
n Число, на которое будет увеличиваться счетчик операций с файлами. Увеличивает на n счетчик числа операций с файлами, задаваемый атрибутом fileOp. Под операциями в данном случае подразумеваются чтение чисел из файла и запись чисел в файл.
References fileOp.
Referenced by ExternalMergeSort::externalSort, ExternalMergeSort::createRuns.
long long Counter::getFileOp()
Получение счетчика файловых операций. /return Число файловых операций, задаваемое атрибутом fileOp.
Получает число файловых операций, задаваемое атрибутом fileOp.
References fileOp.
void Counter::clear()
Обнуление счетчика.
Обнуляет все счетчики, присваивает всем атрибутам 0.
References begTime, endTime, comparsion, fileOp, swaps.
Referenced by Counter, ExternalMergeSort::externalSort.
Counter::~Counter()