FileManager
ifstream* FileManager::iFile
Входной файл.
Поток, используемый для чтения однобайтовой последовательности символьных данных из файла.
ofstream* FileManager::oFile
Выходной файл.
Поток, используемый для записи однобайтовой последовательности символьных данных из файла.
string* FileManager::oFileStr
Путь к выходному файлу.
Строка, содержащая путь к выходному файлу.
string* FileManager::iFileStr
Путь к входному файлу.
Строка, содержащая путь к входному файлу.
FileState FileManager::state
Режим работы с файлами.
Атрибут, азадющий один из режимов работы с файловой системой: NotEnable - режим не задан, WriteOnly - только запись, ReadOnly - Только чтение ReadAndWrite - чтение и запись.
bool FileManager::endOfFile
Флаг достижения конца файла.
true - если в операциях чтения и записи был достигнут конец файла, false - если нет.
void FileManager::closeIFile()
Закрытие входного файла.
Закрывает входной файл, если он существует.
Referenced by ExternalMergeSort::externalSort.
void FileManager::closeOFile()
Закрытие выходного файла.
Закрывает входной файл, сохраняя записанную последовательность, если он существует.
Referenced by ExternalMergeSort::createRuns, ExternalMergeSort::mergeSequencesNew.
bool FileManager::getEndOfFile()
Получение флага конца файла.
Флаг достижения конца файла endOfFile. Возвращает true - если конец файла был достигнут при попытке чтения или записи или false - если конец файла не был достигнут.
Referenced by ExternalMergeSort::mergeSequencesNew.
void FileManager::setEndOfFile(bool b)
Установка флага конца файла в необходимое положение.
b Значение, которое необходимо установить Устанавливает флаг в нужное положение, например сброс флага, если он уже был обработан.
Referenced by ExternalMergeSort::externalSort.
void FileManager::clearOutFile()
Очистка выходного файла.
Затирает выходной файл, вне зависимости от его содержания.
Referenced by ExternalMergeSort::externalSort, ExternalMergeSort::createRuns.
Response FileManager::read(long long *arr, long long size, long long *readNumber)
Чтение входной последовательности из файла.
arr Массив в который необходимо считать числовую последовательность. size Размер последовательности которую необходимо считать. readNumber Число успешно считанных значений из файла. Код успеха или ошибки. Считывает последовательность длиной size в массиив arr, если это возможно. Записывает в readNumber число успешно считанных значений. Возвращает код успеха или ошибки.
References FileNotExist, ReadAndWrite, ReadOnly, FileManagerFail, EndOfFile, Success.
Referenced by ExternalMergeSort::createRuns, ExternalMergeSort::mergeSequencesNew.
Response FileManager::write(long long num)
Запись числа в файл.
num Число, которое необходимо записать в файл. Код успеха или ошибки. Записывает число в выходной файл. Возвращает код успеха или ошибки.
References WriteOnly, ReadAndWrite, FileManagerFail, Success.
Referenced by ExternalMergeSort::createRuns, ExternalMergeSort::mergeSequencesNew.
Response FileManager::write(long long *arr, long long size)
Запись последовательности в файл.
arr Массив, которое необходимо записать в файл. size Длина записываемого в файл массива. Код успеха или ошибки. Записывает последовательность в выходной файл. Возвращает код успеха или ошибки.
References WriteOnly, ReadAndWrite, FileManagerFail, Success.
Response FileManager::setFiles(string file, FileState st)
Определение атрибутов менеджера.
file Строка, содержащая путь к файлу. st Режим менеджера, который необходимо задать. Код успеха или ошибки. Задает атрибуты менеджера, если это возможно. Возвращает код успеха или ошибки.
References ReadOnly, NotEnable, FileNotExist, WriteOnly, Success.
Response FileManager::setFiles(string inFile, string outFile)
Определение атрибутов менеджера.
inFile Строка, содержащая путь к входному файлу. outFile Строка, содержащая путь к выходному файлу. Код успеха или ошибки. Задает атрибуты менеджера, если это возможно. Устанавливает режим ReadAndWrite или возвращает код ошибки. Возвращает код успеха или ошибки.
References NotEnable, FileNotExist, ReadAndWrite, Success.
FileState FileManager::getState()
Проверка состояния менеджера.
Текущее состояние менеджера. Возвращает текущее состояние менеджера.
Referenced by ExternalMergeSort::setParams, UserInterface::setParams.
bool FileManager::checkForEquality()
Проверка входного и выходного файла на эквивалентность.
true, если файлы эквивалентны; false, если нет. Проверяет на эквивалентность входной и выходной файл.
References ReadAndWrite.
Referenced by ExternalMergeSort::setParams, UserInterface::setParams.
Response FileManager::generateSequence(long long size, SeqType type)
Определение атрибутов менеджера.
size Размер генерируемой последовательности. type Тип генерируемой последовательности. Код успеха или ошибки. Генерирует последовательность длиной size одного из типов type: Best - уже упорядоченная последовательность, Average - случайная последовательность, Worst - последовательность, упорядоченная по убыванию.
References ReadAndWrite, WriteOnly, FileNotExist, Average, Best, Worst, Success.
Referenced by UserInterface::callGenerate, UserInterface::callGetDependenceSize, UserInterface::callGetDependenceSizeOfSegments, UserInterface::callGetDependenceType.
FileManager::FileManager(string iFile, FileState state)
Конструктор класса.
file Строка, содержащая путь к файлу. st Режим менеджера, который необходимо задать. Вызывет setParams(...), если код возврата не Success, бросает исключение.
FileManager::FileManager(string inFile, string outFile)
Конструктор класса.
inFile Строка, содержащая путь к файлу. outFile Строка, содержащая путь к выходному файлу. Вызывет setParams(...), если код возврата не Success, бросает исключение.
FileManager::FileManager()
Пустой конструктор класса.
Обнуляет атрибуты.
References NotEnable.
FileManager::~FileManager()
Пустой деструктор класса.
Освобождает выделенную память.
References NotEnable.