.TH "C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/BubbleExternalSort.h" 3 "Вт 15 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/BubbleExternalSort.h \- \fC#include 'ExternalMergeSort\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBBubbleExternalSort\fP"
.br
.RI "Класс внешней многофазной сортировки слиянием, использующий внутреннюю пузырьковую сортировку\&. "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
