.TH "Counter" 3 "Пт 11 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Counter \- \fC#include <Counter\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBCounter\fP ()"
.br
.ti -1c
.RI "void \fBsetBegTime\fP ()"
.br
.ti -1c
.RI "long \fBsetEndTime\fP ()"
.br
.ti -1c
.RI "long \fBgetTimeInterval\fP ()"
.br
.ti -1c
.RI "void \fBincSwaps\fP ()"
.br
.ti -1c
.RI "long \fBgetSwaps\fP ()"
.br
.ti -1c
.RI "void \fBincComparsion\fP (long long n)"
.br
.ti -1c
.RI "long \fBgetComparsion\fP ()"
.br
.ti -1c
.RI "void \fBincFileOp\fP (long long n)"
.br
.ti -1c
.RI "long \fBgetFileOp\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fB~Counter\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "long long \fBbegTime\fP"
.br
.ti -1c
.RI "long long \fBendTime\fP"
.br
.ti -1c
.RI "long long \fBcomparsion\fP"
.br
.ti -1c
.RI "long long \fBfileOp\fP"
.br
.ti -1c
.RI "long long \fBswaps\fP"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "Counter::Counter ()"

.SS "Counter::~Counter ()"

.SH "Методы"
.PP 
.SS "void Counter::clear ()"

.SS "long Counter::getComparsion ()"

.SS "long Counter::getFileOp ()"

.SS "long Counter::getSwaps ()"

.SS "long Counter::getTimeInterval ()"

.SS "void Counter::incComparsion (long long n)"

.SS "void Counter::incFileOp (long long n)"

.SS "void Counter::incSwaps ()"

.SS "void Counter::setBegTime ()"

.SS "long Counter::setEndTime ()"

.SH "Данные класса"
.PP 
.SS "long long Counter::begTime\fC [private]\fP"

.SS "long long Counter::comparsion\fC [private]\fP"

.SS "long long Counter::endTime\fC [private]\fP"

.SS "long long Counter::fileOp\fC [private]\fP"

.SS "long long Counter::swaps\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
