.TH "HeapExternalSort" 3 "Пт 11 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeapExternalSort \- \fC#include <HeapExternalSort\&.h>\fP
.PP
Базовые классы:\fBExternalMergeSort\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBsort\fP (long long *numbers, long long array_size)"
.br
.ti -1c
.RI "\fBHeapExternalSort\fP ()"
.br
.ti -1c
.RI "\fB~HeapExternalSort\fP ()"
.br
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBsiftDown\fP (long long *numbers, long long root, long long bottom)"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Конструктор(ы)"
.PP 
.SS "HeapExternalSort::HeapExternalSort ()"

.SS "HeapExternalSort::~HeapExternalSort ()"

.SH "Методы"
.PP 
.SS "void HeapExternalSort::siftDown (long long * numbers, long long root, long long bottom)\fC [private]\fP"

.SS "void HeapExternalSort::sort (long long * numbers, long long array_size)\fC [virtual]\fP"

.PP
Замещает \fBExternalMergeSort\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
