.TH "QuickExternalSort" 3 "Пт 11 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuickExternalSort \- \fC#include <QuickExternalSort\&.h>\fP
.PP
Базовые классы:\fBExternalMergeSort\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBsort\fP (long long *mas, long long)"
.br
.ti -1c
.RI "\fBQuickExternalSort\fP ()"
.br
.ti -1c
.RI "\fB~QuickExternalSort\fP ()"
.br
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "void \fBqSortI\fP (long long *mas, long long size)"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Конструктор(ы)"
.PP 
.SS "QuickExternalSort::QuickExternalSort ()"

.SS "QuickExternalSort::~QuickExternalSort ()"

.SH "Методы"
.PP 
.SS "void QuickExternalSort::qSortI (long long * mas, long long size)\fC [private]\fP"

.SS "void QuickExternalSort::sort (long long * mas, long long size)\fC [virtual]\fP"

.PP
Замещает \fBExternalMergeSort\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
