.TH "C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/Structures.h" 3 "Вс 27 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/Structures.h \- \fC#include <iostream>\fP
.br

.SS "Перечисления"

.in +1c
.ti -1c
.RI "enum \fBFileState\fP { \fBNotEnable\fP, \fBReadOnly\fP, \fBWriteOnly\fP, \fBReadAndWrite\fP }"
.br
.ti -1c
.RI "enum \fBResponse\fP { \fBSuccess\fP, \fBGenerateError\fP, \fBFileNotExist\fP, \fBSizeError\fP, \fBFileManagerFail\fP, \fBInputAndOutputIsEqual\fP, \fBEndOfFile\fP, \fBMemoryError\fP, \fBParamsFail\fP }"
.br
.ti -1c
.RI "enum \fBLogType\fP { \fBWithOut\fP, \fBCLI\fP, \fBFile\fP }"
.br
.ti -1c
.RI "enum \fBSeqType\fP { \fBBest\fP, \fBAverage\fP, \fBWorst\fP }"
.br
.ti -1c
.RI "enum \fBTypeOfSort\fP { \fBBubble\fP, \fBQuick\fP, \fBHeap\fP, \fBFail\fP }"
.br
.in -1c
.SH "Перечисления"
.PP 
.SS "enum \fBFileState\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fINotEnable \fP\fP
.TP
\fB\fIReadOnly \fP\fP
.TP
\fB\fIWriteOnly \fP\fP
.TP
\fB\fIReadAndWrite \fP\fP
.SS "enum \fBLogType\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fIWithOut \fP\fP
.TP
\fB\fICLI \fP\fP
.TP
\fB\fIFile \fP\fP
.SS "enum \fBResponse\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIGenerateError \fP\fP
.TP
\fB\fIFileNotExist \fP\fP
.TP
\fB\fISizeError \fP\fP
.TP
\fB\fIFileManagerFail \fP\fP
.TP
\fB\fIInputAndOutputIsEqual \fP\fP
.TP
\fB\fIEndOfFile \fP\fP
.TP
\fB\fIMemoryError \fP\fP
.TP
\fB\fIParamsFail \fP\fP
.SS "enum \fBSeqType\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fIBest \fP\fP
.TP
\fB\fIAverage \fP\fP
.TP
\fB\fIWorst \fP\fP
.SS "enum \fBTypeOfSort\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fIBubble \fP\fP
.TP
\fB\fIQuick \fP\fP
.TP
\fB\fIHeap \fP\fP
.TP
\fB\fIFail \fP\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
