.TH "C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/targetver.h" 3 "Пт 11 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/targetver.h \- \fC#include <SDKDDKVer\&.h>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
