.TH "UserInterface" 3 "Вт 15 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserInterface \- 
.SH "Подробное описание"
.PP 
Класс пользовательского интерфейса\&. 


.PP
\fBАвтор:\fP
.RS 4
Alexander Filippov 
.RE
.PP
\fBДата:\fP
.RS 4
Ноябрь 2016 года
.RE
.PP
Класс, отвечающий за взаимодействие пользователя с приложением, а также содержащий в себе некоторые методы, которые позволяют исследовать характеристики сортировки\&. Сообщает об ошибках и выводит результаты в консоль\&. 
.PP
\fC#include <UserInterface\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBinitSession\fP ()"
.br
.RI "Инициализирует сессию взаимодействия с пользователем\&. "
.ti -1c
.RI "\fBUserInterface\fP ()"
.br
.RI "Пустой конструктор класса\&. "
.ti -1c
.RI "\fB~UserInterface\fP ()"
.br
.RI "Деструктор класса\&. "
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "bool \fBcallMethod\fP (int ch)"
.br
.RI "Вызов необходимого метода\&. "
.ti -1c
.RI "void \fBcallGenerate\fP ()"
.br
.RI "Вызов генерации последовательности\&. "
.ti -1c
.RI "void \fBcallSetParams\fP ()"
.br
.RI "Вызов метода, задающего параметры сортировки\&. "
.ti -1c
.RI "void \fBcallSort\fP ()"
.br
.RI "Вызов метода внешней сортировки\&. "
.ti -1c
.RI "void \fBcallEstimate\fP ()"
.br
.RI "Вызов метода оценки характеристик внешней сортировки\&. "
.ti -1c
.RI "void \fBcallGetDependencies\fP ()"
.br
.RI "Вызов метода получения зависимостей характеристик сортировки\&. "
.ti -1c
.RI "\fBResponce\fP \fBsetParams\fP (\fBFileManager\fP *file, long long sizeOfSegments, \fBTypeOfSort\fP type)"
.br
.RI "Метод, задающий параметры сортировки\&. "
.ti -1c
.RI "void \fBcallGetDependenceSize\fP ()"
.br
.RI "Вызов метода получения зависимостей характеристик сортировки от размера\&. "
.ti -1c
.RI "void \fBcallGetDependenceSizeOfSegments\fP ()"
.br
.RI "Вызов метода получения зависимостей характеристик сортировки от размера сегментов\&. "
.ti -1c
.RI "void \fBcallGetDependenceType\fP ()"
.br
.RI "Вызов метода получения зависимостей характеристик сортировки от типа внутренней сортировки\&. "
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "\fBExternalMergeSort\fP * \fBsort\fP"
.br
.RI "Указатель на экземпляр класса сортировки\&. "
.ti -1c
.RI "const string \fBmenu\fP = '0\&. Выход\\n1\&. Сгенерировать последовательность\\n2\&. Задать параметры сортировки\\n3\&. Отсоритровать последовательность\\n4\&. Оценить характеристики сортировки\\n5\&. Получение зависимостей\\n'"
.br
.RI "Константная строка меню\&. "
.ti -1c
.RI "const char * \fBresponceString\fP [9]"
.br
.RI "Константный массив, строк, расшифровывающих коды ошибок\&. "
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "UserInterface::UserInterface ()"

.PP
Пустой конструктор класса\&. Обнуляет атрибуты\&. 
.SS "UserInterface::~UserInterface ()"

.PP
Деструктор класса\&. Освобождает выделенную память\&. 
.SH "Методы"
.PP 
.SS "void UserInterface::callEstimate ()\fC [private]\fP"

.PP
Вызов метода оценки характеристик внешней сортировки\&. Вызывает метод сортировки, если это возможно\&. Выводит отчет характеристик сортировки\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::callGenerate ()\fC [private]\fP"

.PP
Вызов генерации последовательности\&. Получает необходимые параметры для генерации исходной последовательности\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::callGetDependenceSize ()\fC [private]\fP"

.PP
Вызов метода получения зависимостей характеристик сортировки от размера\&. Генерирует входные файлы разной длины\&. Вызывает несколько сортировок с разным размером входной последовательности\&. Получает зависимость характеристик от размера входной последовательности\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::callGetDependenceSizeOfSegments ()\fC [private]\fP"

.PP
Вызов метода получения зависимостей характеристик сортировки от размера сегментов\&. Генерирует тестовую последовательность\&. Вызывает несколько сортировок с разным размером сегментов\&. Получает зависимость характеристик от размера сегментов\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::callGetDependenceType ()\fC [private]\fP"

.PP
Вызов метода получения зависимостей характеристик сортировки от типа внутренней сортировки\&. Генерирует тестовую последовательность\&. Вызывает несколько сортировок с разными типами внутренней сортировки\&. Получает зависимость характеристик от типа внутренней сортировки\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::callGetDependencies ()\fC [private]\fP"

.PP
Вызов метода получения зависимостей характеристик сортировки\&. Вызывает один из методов \fBcallGetDependenceSize()\fP, \fBcallGetDependenceSizeOfSegments()\fP, \fBcallGetDependenceType()\fP\&. Оповещает о возникающих ошибках\&. 
.SS "bool UserInterface::callMethod (int ch)\fC [private]\fP"

.PP
Вызов необходимого метода\&. 
.PP
\fBАргументы:\fP
.RS 4
\fIch\fP Выбор пользователя 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Булево значение - если true, то продолжаем работу программу, если нет, то выход из бесконечного цикла\&.
.RE
.PP
Вызывает метод, получающий необходимые параметры для выбранной пользователем функциональности\&. 
.SS "void UserInterface::callSetParams ()\fC [private]\fP"

.PP
Вызов метода, задающего параметры сортировки\&. Задает параметр sort необходимым указателем на один из классов сортировки\&. Получает необходимые параметры сортировки\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::callSort ()\fC [private]\fP"

.PP
Вызов метода внешней сортировки\&. Вызывает необходимый метод сортировки, если это возможно\&. Оповещает о возникающих ошибках\&. 
.SS "void UserInterface::initSession ()"

.PP
Инициализирует сессию взаимодействия с пользователем\&. Задает бесконечный цикл взаимодействия с пользователем, вызывает getMethod()\&. Завершается если getMethod() возвращает false\&. 
.SS "\fBResponce\fP UserInterface::setParams (\fBFileManager\fP * file, long long sizeOfSegments, \fBTypeOfSort\fP type)\fC [private]\fP"

.PP
Метод, задающий параметры сортировки\&. Вызывает метод, создающий необходимый производный класс сортировки и задающий её параметры\&.
.PP
\fBАргументы:\fP
.RS 4
\fIfile\fP Указатель на класс FileManger, обеспечивающий взаимодействие приложения с файловой системой\&. 
.br
\fIsizeOfSegments\fP Размер сегментов\&. 
.br
\fItype\fP Tип внутренней сортировки\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Код успеха или ошибки\&. 
.RE
.PP

.SH "Данные класса"
.PP 
.SS "const string UserInterface::menu = '0\&. Выход\\n1\&. Сгенерировать последовательность\\n2\&. Задать параметры сортировки\\n3\&. Отсоритровать последовательность\\n4\&. Оценить характеристики сортировки\\n5\&. Получение зависимостей\\n'\fC [private]\fP"

.PP
Константная строка меню\&. 
.SS "const char* UserInterface::responceString[9]\fC [private]\fP"
\fBИнициализатор\fP
.PP
.nf
= { "Успешно", "Ошибка генерации", "Файл не существует", "Ошибка размера", "Ошибка файл-менеджера",
        "Исходный файл и файл результата совпадают", "Достигнут конец файла", "Ошибка выделения памяти", "Параметры не заданы или заданы неверно" }
.fi
.PP
Константный массив, строк, расшифровывающих коды ошибок\&. 
.SS "\fBExternalMergeSort\fP* UserInterface::sort\fC [private]\fP"

.PP
Указатель на экземпляр класса сортировки\&. Позволяет использовать методы внешней многофазной сортировки слиянием\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
