.TH "C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/UserInterface.cpp" 3 "Вс 27 Ноя 2016" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/админ/Documents/ProjectsC++/ExternalMergeSortProduction/ExternalMergeSortProduction/UserInterface.cpp \- \fC#include 'stdafx\&.h'\fP
.br
\fC#include 'UserInterface\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'FileManager\&.h'\fP
.br
\fC#include 'ExternalMergeSort\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'BubbleExternalSort\&.h'\fP
.br
\fC#include 'QuickExternalSort\&.h'\fP
.br
\fC#include 'HeapExternalSort\&.h'\fP
.br
\fC#include <conio\&.h>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen из исходного текста\&.
