var menudata={children:[
{text:'Титульная страница',url:'index.html'},
{text:'Классы',url:'annotated.html',children:[
{text:'Классы',url:'annotated.html'},
{text:'Алфавитный указатель классов',url:'classes.html'},
{text:'Иерархия классов',url:'inherits.html'},
{text:'Члены классов',url:'functions.html',children:[
{text:'Указатель',url:'functions.html',children:[
{text:'b',url:'functions.html#index_b'},
{text:'c',url:'functions.html#index_c'},
{text:'e',url:'functions.html#index_e'},
{text:'f',url:'functions.html#index_f'},
{text:'g',url:'functions.html#index_g'},
{text:'h',url:'functions.html#index_h'},
{text:'i',url:'functions.html#index_i'},
{text:'l',url:'functions.html#index_l'},
{text:'m',url:'functions.html#index_m'},
{text:'o',url:'functions.html#index_o'},
{text:'p',url:'functions.html#index_p'},
{text:'q',url:'functions.html#index_q'},
{text:'r',url:'functions.html#index_r'},
{text:'s',url:'functions.html#index_s'},
{text:'u',url:'functions.html#index_u'},
{text:'w',url:'functions.html#index_w'},
{text:'~',url:'functions.html#index_0x7e'}]},
{text:'Функции',url:'functions_func.html',children:[
{text:'b',url:'functions_func.html#index_b'},
{text:'c',url:'functions_func.html#index_c'},
{text:'e',url:'functions_func.html#index_e'},
{text:'f',url:'functions_func.html#index_f'},
{text:'g',url:'functions_func.html#index_g'},
{text:'h',url:'functions_func.html#index_h'},
{text:'i',url:'functions_func.html#index_i'},
{text:'m',url:'functions_func.html#index_m'},
{text:'p',url:'functions_func.html#index_p'},
{text:'q',url:'functions_func.html#index_q'},
{text:'r',url:'functions_func.html#index_r'},
{text:'s',url:'functions_func.html#index_s'},
{text:'u',url:'functions_func.html#index_u'},
{text:'w',url:'functions_func.html#index_w'},
{text:'~',url:'functions_func.html#index_0x7e'}]},
{text:'Переменные',url:'functions_vars.html'}]}]},
{text:'Файлы',url:'files.html',children:[
{text:'Файлы',url:'files.html'},
{text:'Список членов всех файлов',url:'globals.html',children:[
{text:'Указатель',url:'globals.html'},
{text:'Функции',url:'globals_func.html'},
{text:'Перечисления',url:'globals_enum.html'},
{text:'Элементы перечислений',url:'globals_eval.html'},
{text:'Макросы',url:'globals_defs.html'}]}]}]}
